[packages]
brew = [
  "bat",
  "dust",
  "gh",
  "git",
  "git-delta",
  "jq",
  "neovim",
  "python",
  "ripgrep",
  "starship",
  "tmux",
  "uv",
  "vivid",
  "wget",
  "xz",
  "zsh",
  "zsh-completions",
  "zsh-syntax-highlighting",
  "zstd",
]

brew_darwin_extra = ["gnu-sed", "gnu-tar"]
