#!/bin/zsh

export EDITOR=nvim

typeset -U PATH path

if [ -f /opt/homebrew/bin/brew ]; then
    eval $(/opt/homebrew/bin/brew shellenv zsh)
fi

path=(
    "/opt/homebrew/opt/gnu-tar/libexec/bin"
    "/opt/homebrew/opt/python/libexec/bin"
    $path
)

fpath=(
    "/opt/homebrew/share/zsh/site-functions"
    $fpath
)

# Homebrew options
export HOMEBREW_NO_ENV_HINTS=true
export HOMEBREW_BAT=true

# for rip
export RIP_GRAVEYARD="$HOME/.Trash"


if $(type python3 > /dev/null); then
    path=(
        "$(python3 -m site --user-base)/bin"
        $path
    )
elif $(type python > /dev/null); then
    path=(
        "$(python -m site --user-base)/bin"
        $path
    )
fi

if [ -e "$HOME/.cargo/env" ]; then
    source "$HOME/.cargo/env"
fi

path=(
    "$HOME/.local/bin"
    $path
)

export path

export XZ_DEFAULTS="-T0"
export ZSTD_CLEVEL="6"
export ZSTD_NBTHREADS="0"

# vim: set ft=zsh et :
